version: '3.8'
services:
  server-rangetesmorts:
    name: server-rangetesmorts
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8002:3000'
    volumes:
      - ./data:/app/data # Bind mount to access the SQLite DB
    env_file:
      - backend/.env

  client-rangetesmorts:
    name: client-rangetesmorts
    # Build the Docker image using the Dockerfile in the current directory
    build:
      context: ./frontend

    # Map port 80 in the container to port 3000 on the host machine
    ports:
      - '6000:80'
